-- Sipsi — schema inicial (PostgreSQL / Neon).
-- Convenções: timestamps de registro em UTC ("YYYY-MM-DDTHH:MM:SS"); data/hora de
-- sessão em horário local da clínica ("YYYY-MM-DDTHH:MM"); dinheiro em centavos.

-- ---------------------------------------------------------------- cadastro base
CREATE TABLE psicologo (
  id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome    TEXT NOT NULL,
  crp     TEXT NOT NULL UNIQUE,
  email   TEXT,
  ativo   INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE usuario (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome          TEXT NOT NULL,
  email         TEXT NOT NULL,
  senha_hash    TEXT NOT NULL,
  papel         TEXT NOT NULL DEFAULT 'recepcao' CHECK (papel IN ('admin','psicologo','recepcao')),
  ativo         INTEGER NOT NULL DEFAULT 1,
  psicologo_id  INTEGER REFERENCES psicologo(id),
  criado_em     TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD"T"HH24:MI:SS'))
);

-- Sessões de login. Guardamos só o SHA-256 do token (o token em si fica no cookie).
CREATE UNIQUE INDEX usuario_email_unico ON usuario (lower(email));

CREATE TABLE sessao_login (
  id_hash     TEXT PRIMARY KEY,
  usuario_id  INTEGER NOT NULL REFERENCES usuario(id) ON DELETE CASCADE,
  expira_em   TEXT NOT NULL,
  criado_em   TEXT NOT NULL
);
CREATE INDEX idx_sessao_login_expira ON sessao_login(expira_em);

-- Tentativas de login malsucedidas (limitação de taxa).
CREATE TABLE login_tentativa (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email      TEXT,
  ip         TEXT,
  criado_em  TEXT NOT NULL
);
CREATE INDEX idx_login_tentativa_email ON login_tentativa(email, criado_em);
CREATE INDEX idx_login_tentativa_ip ON login_tentativa(ip, criado_em);

CREATE TABLE paciente (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome             TEXT NOT NULL,
  cpf              TEXT,
  email            TEXT,
  telefone         TEXT,
  data_nascimento  TEXT,
  ativo            INTEGER NOT NULL DEFAULT 1,
  criado_em        TEXT NOT NULL
);

-- ---------------------------------------------------------------------- agenda
CREATE TABLE sessao (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  paciente_id     INTEGER NOT NULL REFERENCES paciente(id),
  psicologo_id    INTEGER NOT NULL REFERENCES psicologo(id),
  data_hora       TEXT NOT NULL,
  duracao_min     INTEGER NOT NULL DEFAULT 50 CHECK (duracao_min > 0),
  valor_centavos  INTEGER NOT NULL DEFAULT 0 CHECK (valor_centavos >= 0),
  status          TEXT NOT NULL DEFAULT 'agendada'
                  CHECK (status IN ('agendada','realizada','falta','cancelada')),
  criado_em       TEXT NOT NULL
);
CREATE INDEX idx_sessao_data ON sessao(data_hora);
CREATE INDEX idx_sessao_paciente ON sessao(paciente_id);

-- ------------------------------------------------------- prontuário (sigiloso)
-- Registro append-only encadeado por hash: cada entrada inclui o hash da anterior
-- do mesmo paciente. Alterar ou apagar uma entrada quebra a cadeia (e os triggers
-- de 0002_imutabilidade.sql já impedem UPDATE/DELETE no próprio banco).
CREATE TABLE prontuario_entrada (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  paciente_id       INTEGER NOT NULL REFERENCES paciente(id),
  seq               INTEGER NOT NULL CHECK (seq >= 1),
  sessao_id         INTEGER CONSTRAINT prontuario_entrada_sessao_id_key UNIQUE REFERENCES sessao(id),
  psicologo_id      INTEGER NOT NULL REFERENCES psicologo(id),
  conteudo          TEXT NOT NULL,
  criado_em         TEXT NOT NULL,
  hash_anterior     TEXT NOT NULL,
  hash_integridade  TEXT NOT NULL,
  CONSTRAINT prontuario_entrada_paciente_seq_key UNIQUE (paciente_id, seq)
);

-- ------------------------------------------------ observações administrativas
CREATE TABLE observacao_administrativa (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  paciente_id  INTEGER NOT NULL REFERENCES paciente(id),
  autor        TEXT,
  conteudo     TEXT NOT NULL,
  criado_em    TEXT NOT NULL
);

-- ------------------------------------------------------------------ financeiro
CREATE TABLE lancamento_financeiro (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sessao_id        INTEGER NOT NULL UNIQUE REFERENCES sessao(id),
  paciente_id      INTEGER NOT NULL REFERENCES paciente(id),
  valor_centavos   INTEGER NOT NULL CHECK (valor_centavos >= 0),
  status           TEXT NOT NULL DEFAULT 'pendente' CHECK (status IN ('pendente','pago')),
  forma_pagamento  TEXT,
  data_vencimento  TEXT,
  data_pagamento   TEXT,
  criado_em        TEXT NOT NULL
);
CREATE INDEX idx_lancamento_venc ON lancamento_financeiro(data_vencimento);

CREATE TABLE nota_fiscal (
  id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lancamento_id       INTEGER NOT NULL UNIQUE REFERENCES lancamento_financeiro(id),
  provedor            TEXT,
  numero_nota         TEXT,
  codigo_verificacao  TEXT,
  status              TEXT NOT NULL DEFAULT 'pendente' CHECK (status IN ('pendente','emitida','erro')),
  valor_iss_centavos  INTEGER,
  mensagem_erro       TEXT,
  url_pdf             TEXT,
  criado_em           TEXT NOT NULL,
  emitida_em          TEXT
);

-- ------------------------------------------- motor de questionários (rastreio)
CREATE TABLE instrumento (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome            TEXT NOT NULL,
  sigla           TEXT NOT NULL,
  fonte_citacao   TEXT NOT NULL,
  ativo           INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE pergunta_instrumento (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  instrumento_id  INTEGER NOT NULL REFERENCES instrumento(id),
  ordem           INTEGER NOT NULL,
  texto           TEXT NOT NULL
);

CREATE TABLE opcao_resposta (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pergunta_id     INTEGER NOT NULL REFERENCES pergunta_instrumento(id),
  texto           TEXT NOT NULL,
  valor_numerico  INTEGER NOT NULL,
  ordem           INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE regra_pontuacao (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  instrumento_id  INTEGER NOT NULL REFERENCES instrumento(id),
  faixa_min       INTEGER NOT NULL,
  faixa_max       INTEGER NOT NULL,
  interpretacao   TEXT NOT NULL,
  nivel_alerta    TEXT NOT NULL DEFAULT 'normal'
                  CHECK (nivel_alerta IN ('normal','atencao','alerta','critico'))
);

CREATE TABLE aplicacao_questionario (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  paciente_id      INTEGER NOT NULL REFERENCES paciente(id),
  instrumento_id   INTEGER NOT NULL REFERENCES instrumento(id),
  status           TEXT NOT NULL DEFAULT 'pendente'
                   CHECK (status IN ('pendente','em_andamento','concluido')),
  data_envio       TEXT NOT NULL,
  data_conclusao   TEXT,
  pontuacao_total  INTEGER,
  interpretacao    TEXT,
  nivel_alerta     TEXT
);

CREATE TABLE resposta_questionario (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  aplicacao_id    INTEGER NOT NULL REFERENCES aplicacao_questionario(id),
  pergunta_id     INTEGER NOT NULL REFERENCES pergunta_instrumento(id),
  opcao_id        INTEGER NOT NULL REFERENCES opcao_resposta(id),
  valor_numerico  INTEGER NOT NULL,
  UNIQUE (aplicacao_id, pergunta_id)
);

-- ---------------------------------------------------------- documentos clínicos
-- conteudo_json guarda os campos preenchidos + um "snapshot" dos dados do paciente
-- e do psicólogo no momento da emissão: o PDF é regenerado a cada download e
-- sai idêntico ao original (nada é gravado em disco).
CREATE TABLE documento_clinico (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  paciente_id    INTEGER NOT NULL REFERENCES paciente(id),
  psicologo_id   INTEGER NOT NULL REFERENCES psicologo(id),
  tipo           TEXT NOT NULL CHECK (tipo IN ('declaracao','atestado','relatorio_psicologico')),
  conteudo_json  TEXT NOT NULL,
  arquivo_pdf    TEXT,
  criado_em      TEXT NOT NULL
);

-- ------------------------------------------------------- trilha de auditoria
CREATE TABLE log_auditoria (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id    INTEGER,
  usuario_nome  TEXT,
  acao          TEXT,
  entidade      TEXT,
  entidade_id   INTEGER,
  paciente_id   INTEGER,
  detalhes      TEXT,
  ip_origem     TEXT,
  criado_em     TEXT NOT NULL
);
CREATE INDEX idx_log_paciente ON log_auditoria(paciente_id);
CREATE INDEX idx_log_criado ON log_auditoria(criado_em);

